---
commitizen:
  name: cz_conventional_commits
  annotated_tag: true
  gpg_sign: true
  bump_message: "bump: version $current_version → $new_version"
  tag_format: v$version
  update_changelog_on_bump: true
  use_shortcuts: true
  version: 1.1.3
  version_scheme: semver
  version_files:
  - cmd/root.go
