---
commitizen:
  annotated_tag: true
  bump_message: "bump: version $current_version \u2192 $new_version"
  gpg_sign: true
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  use_shortcuts: true
  version: 2.0.0
  version_files:
  - cmd/root.go
  version_scheme: semver
