name: Linter
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  golangci:
    if: github.actor != 'dependabot[bot]'
    name: Linting Go code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1               # v7.0.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee  # v9.2.1
        with:
          version: latest
